# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobiles', '0002_auto_20170803_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='general_detail',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_spec',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
