# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.IntegerField(default=984),
        ),
        migrations.AlterField(
            model_name='item',
            name='general_detail',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_spec',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
